services:
  mysql:
    image: mysql:8.0
    container_name: cafe_con_huellas_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: animal_shelter_db
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: cafe_con_huellas_mail
    ports:
      - "1025:1025"   # puerto SMTP (Spring lo usa para enviar)
      - "8025:8025"   # interfaz web para ver los emails
    restart: unless-stopped

  backend:
    build: .
    container_name: cafe_con_huellas_backend
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/animal_shelter_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      mysql:
        condition: service_healthy
      mailpit:
        condition: service_started

volumes:
  mysql_data:


