spring.application.name=cafe_con_huellas

# Configuración base de datos:
spring.datasource.url=jdbc:mysql://localhost:3306/animal_shelter_db
spring.datasource.username=root
spring.datasource.password=Golesbians1234-
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configuración del servidor
server.port=8080
server.error.include-message=always

# Formato de fechas (JSON / DATES)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Europe/Madrid

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
