# HAY QUE MODIFICAR TODO ESTE FICHERO EN PRODUCCIÓN CUANDO SE SEPAN LOS DOMINIOS

# URL base del frontend en producción
app.frontend.url=https://tu-dominio.com

# Base de datos de producción
spring.datasource.url=jdbc:mysql://tu-servidor:3306/animal_shelter_db

# JWT más seguro en producción
app.jwt.secret=una_clave_mucho_mas_larga_y_segura_para_produccion
